// import mockBooks from 'books-mock-api';
export const books = [
  {
    title: "Northanger Abbey",
    id: 1,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Austen, Jane",
    year_written: 1814,
    edition: "Penguin",
    price: 18.2,
  },
  {
    title: "War and Peace",
    id: 2,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolstoy, Leo",
    year_written: 1865,
    edition: "Penguin",
    price: 12.7,
  },
  {
    title: "Anna Karenina",
    id: 3,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolstoy, Leo",
    year_written: 1875,
    edition: "Penguin",
    price: 13.5,
  },
  {
    title: "Mrs. Dalloway",
    id: 4,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Woolf, Virginia",
    year_written: 1925,
    edition: "Harcourt Brace",
    price: 25,
  },
  {
    title: "The Hours",
    id: 5,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Cunnningham, Michael",
    year_written: 1999,
    edition: "Harcourt Brace",
    price: 12.35,
  },
  {
    title: "Huckleberry Finn",
    id: 6,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Twain, Mark",
    year_written: 1865,
    edition: "Penguin",
    price: 5.76,
  },
  {
    title: "Bleak House",
    id: 7,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Dickens, Charles",
    year_written: 1870,
    edition: "Random House",
    price: 5.75,
  },
  {
    title: "Tom Sawyer",
    id: 8,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Twain, Mark",
    year_written: 1862,
    edition: "Random House",
    price: 7.75,
  },
  {
    title: "A Room of One's Own",
    id: 9,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Woolf, Virginia",
    year_written: 1922,
    edition: "Penguin",
    price: 29,
  },
  {
    title: "Harry Potter",
    id: 10,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
  {
    title: "One Hundred Years of Solitude",
    id: 11,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Marquez",
    year_written: 1967,
    edition: "Harper  Perennial",
    price: 14.0,
  },
  {
    title: "Hamlet, Prince of Denmark",
    id: 12,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Shakespeare",
    year_written: 1603,
    edition: "Signet  Classics",
    price: 7.95,
  },
  {
    title: "Lord of the Rings",
    id: 13,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 14,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 15,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 16,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 17,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 18,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 19,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 20,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 21,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 22,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 23,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Lord of the Rings",
    id: 24,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Tolkien, J.R.",
    year_written: 1937,
    edition: "Penguin",
    price: 27.45,
  },
  {
    title: "Harry Potter",
    id: 25,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
  {
    title: "Harry Potter",
    id: 26,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
  {
    title: "Harry Potter",
    id: 27,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
  {
    title: "Harry Potter",
    id: 28,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
];

// export const newBooks= mockBooks.getBooks();
